trigger:
- main

pool: may-pool

variables:
  nodeVersion: '16.x'

steps:

- task: NodeTool@0
  inputs:
    versionSpec: $(nodeVersion)
  displayName: Install NodeJS

- script: |
    npm install
  displayName: Install Dependencies

- script: |
    npm run build
  displayName: Build React App

- script: |
    sudo rm -rf /var/www/reactapp/*
    sudo cp -r build/* /var/www/reactapp/
  displayName: Deploy to VM